# Generated by Django 4.1.2 on 2022-10-04 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=34)),
                ('degree', models.CharField(max_length=34)),
                ('email', models.EmailField(max_length=34)),
                ('Address', models.CharField(max_length=334)),
                ('pin', models.IntegerField()),
                ('dob', models.DateField()),
                ('country', models.CharField(max_length=34)),
                ('selfintro', models.CharField(max_length=34)),
                ('image', models.FileField(upload_to='')),
            ],
        ),
    ]
