# Generated by Django 4.1.2 on 2022-10-06 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_students_address_alter_students_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='pin',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
