# Generated by Django 4.1.2 on 2022-10-08 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_students_pin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='Address',
            new_name='address',
        ),
        migrations.AlterField(
            model_name='students',
            name='selfintro',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
